# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='park',
            name='open_time',
        ),
        migrations.AddField(
            model_name='park',
            name='operating_hours',
            field=models.TextField(default='Sorry, no operating hours found'),
        ),
        migrations.AddField(
            model_name='park',
            name='phone_number',
            field=models.CharField(default='Sorry, no phone number found', max_length=20),
        ),
        migrations.AddField(
            model_name='park',
            name='website',
            field=models.CharField(default='Sorry, no website found', max_length=255),
        ),
    ]
