# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0011_auto_20190626_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TextField()),
                ('tuesday', models.TextField()),
                ('wednesday', models.TextField()),
                ('thursday', models.TextField()),
                ('friday', models.TextField()),
                ('saturday', models.TextField()),
                ('sunday', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
