# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0003_auto_20190626_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
