# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0009_auto_20190626_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='operating_hours',
            field=models.CharField(default='', max_length=255),
        ),
    ]
