# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0012_operatinghours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatingHours',
        ),
    ]
